### ISSUE TITLE
About Github workflows

### ISSUE THREAD

**Issue by pehlicd** [Dentrax/falco-gpt#1]
Hi,
Great project! I realized there isn't any workflow to ensure ci. If contributions are welcome, I would like to add this functionality with using `docker/build-push-action`. And also adding `Dockerfile` as well.

**Comment by developer-guy** [comment]
we already have plans, if you want to collaborate, we'd be happy to collaborate!

**Comment by Dentrax** [comment]
Cool idea, +1!

**Comment by pehlicd** [comment]
Since pr is merged, closing this issue. Thanks...
